export const Main_route = "/main"
export const Login_route = "/login"
export const Reg_route = "/reg"
export const Profile_route ="/user/profile"
export const Passive_voice_route = "/article/passive_voice"
export const Sequence_tense_route = "/article/sequence_tense"
export const Course_route = "/course"
export const Zapis_na_course_route = "/course/zapis"